#!/bin/bash

declare -r sync_comm="rsync -az --update"

while [[ $# -ne 0 ]]; do
	case "$1" in
		-h|--help)
			printf "Usage: filesync [options]\n"
			printf "\n"
			printf "Options:\n"
			printf "  %-28s %s\n" "-h, --help" "display this text"
			printf "\n"
			exit 0
			;;
	esac
	shift
done

target=$(pwd)
if [[ ! -f "$target/.fsync" ]]; then
	echo "Fatal: not a filesync directory; .fsync not found." >&2
	exit 1
fi

remote_path="$(< "$target/.fsync")"
remote_path="${remote_path%/}"
if [[ -z "$remote_path" ]]; then
	echo "Fatal: no remote path specified in $target/.fsync" >&2
	exit 1
fi

echo "Syncing $(pwd)..."

if echo "$remote_path" | grep ':' >/dev/null; then
	remote_host="${remote_path%%:*}"
	remote_host_path="${remote_path#*:}"
	ssh "$remote_host" "mkdir -p $remote_host_path"
fi

_run_sync() {
	if ! $sync_comm "$remote_path/" "$target"; then
		echo "Error: failed to pull changes" >&2
		return 1
	fi
	if ! $sync_comm "$target/" "$remote_path"; then
		echo "Error: fail to push changes" >&2
		return 1
	fi
}

if _run_sync; then
	echo "Sync successful"
else
	echo "Sync failed" >&2
	exit 1
fi
